create table
  public."Country" (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    code character varying not null,
    population bigint null,
    constraint Country_pkey primary key (id)
  ) tablespace pg_default;

INSERT INTO "public"."Country" ("id", "created_at", "name", "code", "population") VALUES ('1', '2024-12-18 15:09:36.923786+00', 'Unated States of America', 'USA', null), ('2', '2024-12-18 15:09:56.821743+00', 'Serbia', 'SA', null);

create table
  public."Actor" (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    last_name character varying not null,
    first_name character varying null,
    date_of_birth date null,
    country_id bigint null,
    constraint Actor_pkey primary key (id),
    constraint Actor_country_id_fkey foreign key (country_id) references "Country" (id)
  ) tablespace pg_default;

INSERT INTO "public"."Actor" ("id", "created_at", "last_name", "first_name", "date_of_birth", "country_id") VALUES ('1', '2024-12-18 15:10:55.031064+00', 'Cruise', 'Tom', '1956-12-12', '1'), ('2', '2024-12-18 15:11:33.635744+00', 'Samardžić', 'Ljubiša', '1947-05-13', '2');

CREATE OR REPLACE FUNCTION get_actors_with_country() RETURNS TABLE (
    id int8,
    last_name varchar,
    first_name varchar,
    country_id int8,
    country_name varchar,
    country_code varchar,
    date_of_birth date
) AS $$
BEGIN
    RETURN QUERY
    SELECT a.id, a.last_name, a.first_name, a.country_id, c.name as country_name, c.code as country_code, a.date_of_birth
    FROM public."Actor" a
    JOIN public."Country" c ON a.country_id = c.id;
END;
$$ LANGUAGE plpgsql;
